const sampleData = {
  products: [

    
  {
    name: 'Jasmine',
    slug: 'jasmine-plant',
    category: 'Flowering Plant',
    description: 'A fragrant flowering plant that blooms best in warm, sunny spots.',
    images: [
      '/images/plants/jasmine-1.jpg',
      '/images/plants/jasmine-2.jpg',
    ],
    price: 199,
    brand: 'Nature Bloom',
    rating: 4.7,
    numReviews: 24,
    stock: 12,
    isFeatured: true,
    banner: 'banner-jasmine.jpg',
  },
  {
    name: 'Hibiscus',
    slug: 'hibiscus-plant',
    category: 'Flowering Plant',
    description: 'A tropical shrub with large, colorful blooms loved by pollinators.',
    images: [
      '/images/plants/hibiscus-1.jpg',
      '/images/plants/hibiscus-2.jpg',
    ],
    price: 179,
    brand: 'Green Valley',
    rating: 4.6,
    numReviews: 19,
    stock: 0,
    isFeatured: false,
    banner: 'banner-hibiscus.jpg',
  },
  {
    name: 'Rose',
    slug: 'rose-plant',
    category: 'Flowering Plant',
    description: 'Classic garden favorite known for its beauty and fragrance.',
    images: [
      '/images/plants/rose-1.jpg',
      '/images/plants/rose-2.jpg',
    ],
    price: 149,
    brand: 'Bloom Craft',
    rating: 4.8,
    numReviews: 31,
    stock: 20,
    isFeatured: true,
    banner: 'banner-rose.jpg',
  },
  {
    name: 'Pomegranate',
    slug: 'pomegranate-plant',
    category: 'Fruit Plant',
    description: 'A hardy fruit-bearing plant producing sweet and tangy red fruits.',
    images: [
      '/images/plants/pomegranate-1.jpg',
      '/images/plants/pomegranate-2.jpg',
    ],
    price: 249,
    brand: 'Fruit Grove',
    rating: 4.5,
    numReviews: 14,
    stock: 10,
    isFeatured: false,
    banner: 'banner-pomegranate.jpg',
  },
  {
    name: 'Mango',
    slug: 'mango-plant',
    category: 'Fruit Plant',
    description: 'A tropical fruit tree producing juicy and aromatic mangoes.',
    images: [
      '/images/plants/mango-1.jpg',
      '/images/plants/mango-2.jpg',
    ],
    price: 299,
    brand: 'Tropical Roots',
    rating: 4.9,
    numReviews: 27,
    stock: 8,
    isFeatured: true,
    banner: 'banner-mango.jpg',
  },
  {
    name: 'Chiku (Sapota)',
    slug: 'chiku-plant',
    category: 'Fruit Plant',
    description: 'An evergreen fruit tree producing sweet, brown, and grainy fruits.',
    images: [
      '/images/plants/chiku-1.jpg',
      '/images/plants/chiku-2.jpg',
    ],
    price: 239,
    brand: 'Green Leaf Nursery',
    rating: 4.4,
    numReviews: 11,
    stock: 9,
    isFeatured: false,
    banner: 'banner-chiku.jpg',
  },
  {
    name: 'Lemon',
    slug: 'lemon-plant',
    category: 'Fruit Plant',
    description: 'A citrus plant that produces tangy, vitamin-rich lemons year-round.',
    images: [
      '/images/plants/lemon-1.jpg',
      '/images/plants/lemon-2.jpg',
    ],
    price: 189,
    brand: 'Citrus Garden',
    rating: 4.6,
    numReviews: 22,
    stock: 13,
    isFeatured: false,
    banner: 'banner-lemon.jpg',
  },



    // {
    //   name: 'Polo Sporting Stretch Shirt',
    //   slug: 'polo-sporting-stretch-shirt',
    //   category: "Men's Dress Shirts",
    //   description: 'Classic Polo style with modern comfort',
    //   images: [
    //     '/images/sample-products/p1-1.jpg',
    //     '/images/sample-products/p1-2.jpg',
    //   ],
    //   price: 59.99,
    //   brand: 'Polo',
    //   rating: 4.5,
    //   numReviews: 10,
    //   stock: 5,
    //   isFeatured: true,
    //   banner: 'banner-1.jpg',
    // },
    // {
    //   name: 'Brooks Brothers Long Sleeved Shirt',
    //   slug: 'brooks-brothers-long-sleeved-shirt',
    //   category: "Men's Dress Shirts",
    //   description: 'Timeless style and premium comfort',
    //   images: [
    //     '/images/sample-products/p2-1.jpg',
    //     '/images/sample-products/p2-2.jpg',
    //   ],
    //   price: 85.9,
    //   brand: 'Brooks Brothers',
    //   rating: 4.2,
    //   numReviews: 8,
    //   stock: 10,
    //   isFeatured: true,
    //   banner: 'banner-2.jpg',
    // },
    // {
    //   name: 'Tommy Hilfiger Classic Fit Dress Shirt',
    //   slug: 'tommy-hilfiger-classic-fit-dress-shirt',
    //   category: "Men's Dress Shirts",
    //   description: 'A perfect blend of sophistication and comfort',
    //   images: [
    //     '/images/sample-products/p3-1.jpg',
    //     '/images/sample-products/p3-2.jpg',
    //   ],
    //   price: 99.95,
    //   brand: 'Tommy Hilfiger',
    //   rating: 4.9,
    //   numReviews: 3,
    //   stock: 0,
    //   isFeatured: false,
    //   banner: null,
    // },
    // {
    //   name: 'Calvin Klein Slim Fit Stretch Shirt',
    //   slug: 'calvin-klein-slim-fit-stretch-shirt',
    //   category: "Men's Dress Shirts",
    //   description: 'Streamlined design with flexible stretch fabric',
    //   images: [
    //     '/images/sample-products/p4-1.jpg',
    //     '/images/sample-products/p4-2.jpg',
    //   ],
    //   price: 39.95,
    //   brand: 'Calvin Klein',
    //   rating: 3.6,
    //   numReviews: 5,
    //   stock: 10,
    //   isFeatured: false,
    //   banner: null,
    // },
    // {
    //   name: 'Polo Ralph Lauren Oxford Shirt',
    //   slug: 'polo-ralph-lauren-oxford-shirt',
    //   category: "Men's Dress Shirts",
    //   description: 'Iconic Polo design with refined oxford fabric',
    //   images: [
    //     '/images/sample-products/p5-1.jpg',
    //     '/images/sample-products/p5-2.jpg',
    //   ],
    //   price: 79.99,
    //   brand: 'Polo',
    //   rating: 4.7,
    //   numReviews: 18,
    //   stock: 6,
    //   isFeatured: false,
    //   banner: null,
    // },
    // {
    //   name: 'Polo Classic Pink Hoodie',
    //   slug: 'polo-classic-pink-hoodie',
    //   category: "Men's Sweatshirts",
    //   description: 'Soft, stylish, and perfect for laid-back days',
    //   images: [
    //     '/images/sample-products/p6-1.jpg',
    //     '/images/sample-products/p6-2.jpg',
    //   ],
    //   price: 99.99,
    //   brand: 'Polo',
    //   rating: 4.6,
    //   numReviews: 12,
    //   stock: 8,
    //   isFeatured: true,
    //   banner: null,
    // },
  ],
};

export default sampleData;
